### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by edvilme** [edvilme/animated-web-components#15]
Due to Hacktoverfest, we are having more contributors (and expect new ones to continue arriving afterwards). We could set up a couple of rules to contribute. I propose:
1. All contributors who publish a PR will be added to the Contributors section of the README. Thanks @Smollet777 
2. Looking into existing documentation and issues before attempting to propose a new feature.
3. Breaking changes are allowed but they must be discussed first. Will add a section in the Discussions tab.
4. Any type of suggestion (changing variable names, refactoring for efficiency, community stuff is greatly appreciated).
5. Feel free to add the standard rules as well. 

I know this is kind of meta, but it could benefit the project a lot and is an easy first issue

**Comment by izhar360** [comment]
assign me please
